# Generated by Django 3.2.6 on 2021-10-05 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_message'),
        ('project', '0012_review_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-vote_ratio', '-vote_total', 'title']},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('owner', 'project')},
        ),
    ]
