# Generated by Django 3.2.6 on 2021-10-05 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_message_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
