# Generated by Django 3.2.6 on 2021-09-22 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, default='devsearch@email.com', max_length=254, null=True),
        ),
    ]
