# Generated by Django 3.2.6 on 2021-10-05 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20211005_1506'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
